#!python
pbub=r"""
{"config":{},
  "machines":{"main":{"diags":{"main":{"nodes":{"16":{"links":[35],
              "params":["_grab = _grab[:, :, ::-1]  #convert bgr to rgb","_im=Image.fromarray(_grab,mode='RGB')",""],
              "pos":[53,39],
              "size":[15,2],
              "type":"PYTHON"},
            "22":{"links":[36],
              "params":["test",["closeable","False"]],
              "pos":[38,11],
              "size":[9,2],
              "type":"PAGE"},
            "24":{"links":[16],
              "params":["ret, _grab = video_capture.read()","_grey = cv2.cvtColor(_grab, cv2.COLOR_BGR2GRAY)",
                "faces = faceCascade.detectMultiScale(","            _grey,","            scaleFactor=1.1,",
                "            minNeighbors=5,","            minSize=(30, 30),","            #flags=cv2.cv.CV_HAAR_SCALE_IMAGE",
                "        )",""],
              "pos":[53,29],
              "size":[19,9],
              "type":"PYTHON"},
            "25":{"links":[43],
              "params":["_pg.icons['image']"],
              "pos":[38,16],
              "size":[9,1],
              "type":"IMAGE"},
            "28":{"links":[30,39],
              "params":["x,y,w,h","faces"],
              "pos":[38,43],
              "size":[7,2],
              "type":"FOR"},
            "29":{"links":[28],
              "params":[],
              "pos":[34,49],
              "size":[3,1],
              "type":"LOOP"},
            "30":{"links":[29],
              "params":["w","h",["x","x"],["y","y"],["colour","#ff0188"],["line_width","3"]],
              "pos":[40,46],
              "size":[7,5],
              "type":"RECT"},
            "32":{"links":[40],
              "params":["# Set up webcam video","import cv2","import sysconfig","from PIL import Image","import os",
                "data_folder=sysconfig.get_paths()['purelib']+os.sep+'cv2'+os.sep+'data'+os.sep",
                "faceCascade=cv2.CascadeClassifier(data_folder+'haarcascade_frontalface_alt.xml')",
                "video_capture = cv2.VideoCapture(chan)",""],
              "pos":[38,20],
              "size":[29,8],
              "type":"PYTHON"},
            "35":{"links":[37],
              "params":[["_pg[0].image","_im"]],
              "pos":[53,42],
              "size":[7,1],
              "type":"ASSIGN"},
            "36":{"links":[25],
              "params":[],
              "pos":[38,14],
              "size":[5,1],
              "type":"PAGE_CLEAR"},
            "37":{"links":[28],
              "params":["_pg.current.table","range(1,20)"],
              "pos":[53,44],
              "size":[9,2],
              "type":"DELETE"},
            "39":{"links":[40,42,42],
              "params":["wait","Timer","Esc","WinClose"],
              "pos":[38,34],
              "size":[5,4],
              "type":"WAIT"},
            "40":{"links":[24],
              "params":[["_os.timer","0.1,'t'"]],
              "pos":[38,30],
              "size":[9,1],
              "type":"ASSIGN"},
            "42":{"links":[44],
              "params":["video_capture.release()"],
              "pos":[29,40],
              "size":[9,1],
              "type":"PYTHON"},
            "43":{"links":[32],
              "params":[["chan","0"]],
              "pos":[38,18],
              "size":[5,1],
              "type":"ASSIGN"},
            "44":{"links":[0],
              "params":[],
              "pos":[29,42],
              "size":[5,1],
              "type":"PAGE_CLOSE"},
            "46":{"links":[],
              "params":["This is a simple program to demonstrate<br />face detection using the 'opencv' library.<br /><br />Connect a web-cam and run!",
                "TkDefaultFont,14","#00008c"],
              "pos":[23.611111111111107,-3.833333333333333],
              "size":[0,0],
              "type":"TEXT"},
            "47":{"links":[22],
              "params":["#Check imports","import sys","import subprocess","import sysconfig","","for prog in ['opencv-python',",
                "             'matplotlib',","             'numpy']:","    try:",
                "        subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", prog])","    except Exception as e_2:",
                "        print('Failed to install',prog,e_2)","",""],
              "pos":[20,6],
              "size":[25,13],
              "type":"PYTHON"}},
          "signature":{"linknames":[],
            "loop":0,
            "params":["#DDD"],
            "pos":[31,3],
            "size":[7,1],
            "start":47,
            "undoable":true},
          "vars":{"c":639,
            "chan":0,
            "data_folder":"/home/barney/python_virtual_environments/bubbl3.12/lib/python3.12/site-packages/cv2/data/",
            "prog":"numpy",
            "ret":true,
            "this":"wrongful"}}},
      "tables":{"_config":{"_table":{"defaults":["",""],
            "fieldnames":["key:none","value:none"],
            "name":"_config",
            "rows":[["scale","normal"],["tkinterfiledialog",false],["loglevel",2],["ideloglevel",2]]}},
        "_history":{"_table":{"defaults":["",""],
            "fieldnames":["key:none","value:none"],
            "name":"_history",
            "rows":[["DEFAULT","2"]]}}}}}}
"""
import sys
import os
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__))+os.sep+'bubblib')
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__))+os.sep+'bubblidelib')
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__))+os.sep+'bubblib.zip')

from bubblib.simplebubblapp import Runner
from bubblib.uiserver import ui
if __name__=='__main__':
    Runner(pbub)
    ui.run()
